### ISSUE TITLE
imx-boot missing when building core-image-base

### ISSUE THREAD

**Issue by mirzak** [mirzak/meta-coral#66]
Testing a build on yocto/master, `imx-boot` does not get build when running:

```sh
bitbake core-image-base
```

Fails with:

<details><summary>Details</summary>
<p>

```
ERROR: core-image-base-1.0-r0 do_image_wic: ExecutionError('/home/ubuntu/src/coral/build/tmp/work/coral_dev-fslc-linux/core-image-base/1.0/temp/run.do_image_wic.1008013', 1, None, None)
ERROR: Logfile of failure stored in: /home/ubuntu/src/coral/build/tmp/work/coral_dev-fslc-linux/core-image-base/1.0/temp/log.do_image_wic.1008013
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/home/ubuntu/src/coral/sources/meta-coral/recipes-bsp/u-boot/u-boot-coral_2019.04.bb:do_populate_sysroot', '/home/ubuntu/src/coral/sources/poky/meta/recipes-core/glibc/cross-localedef-native_2.39.bb:do_populate_sysroot', '/home/ubuntu/src/coral/sources/poky/meta/recipes-core/glibc/ldconfig-native_2.12.1.bb:do_populate_sysroot', '/home/ubuntu/src/coral/sources/poky/meta/recipes-devtools/qemu/qemuwrapper-cross_1.0.bb:do_populate_sysroot', '/home/ubuntu/src/coral/sources/poky/meta/recipes-kernel/kmod/depmodwrapper-cross_1.0.bb:do_populate_sysroot', 'virtual:native:/home/ubuntu/src/coral/sources/poky/meta/recipes-core/update-rc.d/update-rc.d_0.8.bb:do_populate_sysroot', 'virtual:native:/home/ubuntu/src/coral/sources/poky/meta/recipes-devtools/createrepo-c/createrepo-c_1.1.0.bb:do_populate_sysroot', 'virtual:native:/home/ubuntu/src/coral/sources/poky/meta/recipes-devtools/dnf/dnf_4.19.2.bb:do_populate_sysroot', 'virtual:native:/home/ubuntu/src/coral/sources/poky/meta/recipes-devtools/dosfstools/dosfstools_4.2.bb:do_populate_sysroot', 'virtual:native:/home/ubuntu/src/coral/sources/poky/meta/recipes-devtools/e2fsprogs/e2fsprogs_1.47.0.bb:do_populate_sysroot', 'virtual:native:/home/ubuntu/src/coral/sources/poky/meta/recipes-devtools/fdisk/gptfdisk_1.0.10.bb:do_populate_sysroot', 'virtual:native:/home/ubuntu/src/coral/sources/poky/meta/recipes-devtools/makedevs/makedevs_1.0.1.bb:do_populate_sysroot', 'virtual:native:/home/ubuntu/src/coral/sources/poky/meta/recipes-devtools/mtools/mtools_4.0.43.bb:do_populate_sysroot', 'virtual:native:/home/ubuntu/src/coral/sources/poky/meta/recipes-devtools/opkg-utils/opkg-utils_0.6.3.bb:do_populate_sysroot', 'virtual:native:/home/ubuntu/src/coral/sources/poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/home/ubuntu/src/coral/sources/poky/meta/recipes-devtools/rpm/rpm_4.19.1.1.bb:do_populate_sysroot', 'virtual:native:/home/ubuntu/src/coral/sources/poky/meta/recipes-extended/parted/parted_3.6.bb:do_populate_sysroot', 'virtual:native:/home/ubuntu/src/coral/sources/poky/meta/recipes-extended/pigz/pigz_2.8.bb:do_populate_sysroot', 'virtual:native:/home/ubuntu/src/coral/sources/poky/meta/recipes-support/bmaptool/bmaptool_git.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: ['dosfstools-native', 'gptfdisk-native', 'mtools-native', 'parted-native']
| NOTE: Skipping as already exists in sysroot: ['coral-boot-script', 'u-boot-coral', 'gettext-minimal-native', 'cross-localedef-native', 'glibc', 'ldconfig-native', 'cmake-native', 'gcc-runtime', 'libgcc', 'libtool-native', 'm4-native', 'qemu-native', 'qemuwrapper-cross', 'texinfo-dummy-native', 'depmodwrapper-cross', 'linux-libc-headers', 'openssl-native', 'coreutils-native', 'expat-native', 'gettext-native', 'glib-2.0-native', 'libxml2-native', 'ncurses-native', 'readline-native', 'update-rc.d-native', 'util-linux-libuuid-native', 'util-linux-native', 'zlib-native', 'createrepo-c-native', 'dnf-native', 'e2fsprogs-native', 'elfutils-native', 'file-native', 'flex-native', 'gnu-config-native', 'json-c-native', 'libcomps-native', 'libdnf-native', 'libedit-native', 'libmodulemd-native', 'librepo-native', 'lua-native', 'make-native', 'makedevs-native', 'opkg-utils-native', 'perl-native', 'pseudo-native', 'python3-build-native', 'python3-flit-core-native', 'python3-iniparse-native', 'python3-installer-native', 'python3-packaging-native', 'python3-pyproject-hooks-native', 'python3-setuptools-native', 'python3-six-native', 'python3-wheel-native', 'python3-native', 'rpm-native', 'swig-native', 'bzip2-native', 'libarchive-native', 'libidn2-native', 'libnsl2-native', 'libsolv-native', 'libtirpc-native', 'lzlib-native', 'pigz-native', 'shadow-native', 'unzip-native', 'xz-native', 'zstd-native', 'gobject-introspection-native', 'kmod-native', 'acl-native', 'attr-native', 'bmaptool-native', 'curl-native', 'debianutils-native', 'gdbm-native', 'gmp-native', 'gnutls-native', 'libtasn1-native', 'gpgme-native', 'itstool-native', 'libassuan-native', 'libbsd-native', 'libcap-ng-native', 'libcap-native', 'libcheck-native', 'libffi-native', 'libgcrypt-native', 'libgpg-error-native', 'libmd-native', 'libmicrohttpd-native', 'libpcre2-native', 'libunistring-native', 'libyaml-native', 'nettle-native', 'popt-native', 'shared-mime-info-native', 'sqlite3-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing python function set_image_size
| DEBUG: 708692.400000 = 545148 * 1.300000
| DEBUG: 708692.400000 = max(708692.400000, 65536)[708692.400000] + 0
| DEBUG: 708693.000000 = int(708692.400000)
| DEBUG: 708693 = aligned(708693)
| DEBUG: returning 708693
| DEBUG: Python function set_image_size finished
| DEBUG: Executing shell function do_image_wic
| INFO: Creating image(s)...
| 
| Traceback (most recent call last):
|   File "/home/ubuntu/src/coral/sources/poky/scripts/lib/wic/filemap.py", line 136, in _open_image_file
|     self._f_image = open(self._image_path, 'rb')
|                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
| FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/src/coral/build/tmp/deploy/images/coral-dev/imx-boot'
| 
| During handling of the above exception, another exception occurred:
| 
| Traceback (most recent call last):
|   File "/home/ubuntu/src/coral/sources/poky/scripts/wic", line 547, in <module>
|     sys.exit(main(sys.argv[1:]))
|              ^^^^^^^^^^^^^^^^^^
|   File "/home/ubuntu/src/coral/sources/poky/scripts/wic", line 542, in main
|     return hlp.invoke_subcommand(args, parser, hlp.wic_help_usage, subcommands)
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/home/ubuntu/src/coral/sources/poky/scripts/lib/wic/help.py", line 83, in invoke_subcommand
|     subcmd[0](args, usage)
|   File "/home/ubuntu/src/coral/sources/poky/scripts/wic", line 222, in wic_create_subcommand
|     engine.wic_create(wks_file, rootfs_dir, bootimg_dir, kernel_dir,
|   File "/home/ubuntu/src/coral/sources/poky/scripts/lib/wic/engine.py", line 190, in wic_create
|     plugin.do_create()
|   File "/home/ubuntu/src/coral/sources/poky/scripts/lib/wic/plugins/imager/direct.py", line 98, in do_create
|     self.create()
|   File "/home/ubuntu/src/coral/sources/poky/scripts/lib/wic/plugins/imager/direct.py", line 186, in create
|     self._image.prepare(self)
|   File "/home/ubuntu/src/coral/sources/poky/scripts/lib/wic/plugins/imager/direct.py", line 367, in prepare
|     part.prepare(imager, imager.workdir, imager.oe_builddir,
|   File "/home/ubuntu/src/coral/sources/poky/scripts/lib/wic/partition.py", line 188, in prepare
|     plugin.do_prepare_partition(self, srcparams_dict, creator,
|   File "/home/ubuntu/src/coral/sources/poky/scripts/lib/wic/plugins/source/rawcopy.py", line 102, in do_prepare_partition
|     sparse_copy(src, dst)
|   File "/home/ubuntu/src/coral/sources/poky/scripts/lib/wic/filemap.py", line 534, in sparse_copy
|     fmap = api(src_fname)
|            ^^^^^^^^^^^^^^
|   File "/home/ubuntu/src/coral/sources/poky/scripts/lib/wic/filemap.py", line 513, in filemap
|     return FilemapFiemap(image, log)
|            ^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/home/ubuntu/src/coral/sources/poky/scripts/lib/wic/filemap.py", line 330, in __init__
|     _FilemapBase.__init__(self, image, log)
|   File "/home/ubuntu/src/coral/sources/poky/scripts/lib/wic/filemap.py", line 95, in __init__
|     self._open_image_file()
|   File "/home/ubuntu/src/coral/sources/poky/scripts/lib/wic/filemap.py", line 138, in _open_image_file
|     raise Error("cannot open image file '%s': %s"
| wic.filemap.Error: cannot open image file '/home/ubuntu/src/coral/build/tmp/deploy/images/coral-dev/imx-boot': [Errno 2] No such file or directory: '/home/ubuntu/src/coral/build/tmp/deploy/images/coral-dev/imx-boot'
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/ubuntu/src/coral/sources/poky/meta/recipes-core/images/core-image-base.bb:do_image_wic) failed with exit code '1'
```

</p>
</details> 

Possible to workaround with:

```
bitbake imx-boot && bitbake core-image-base
```

**Comment by asac** [comment]
I think this one helps.
